name: Enforce Standards

on:
  push:
    branches:
      - '**' # Runs on all branches

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: 'commitlint.config.js'

  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Branch name: $BRANCH_NAME"
          if ! [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/[a-z0-9._-]+$ ]]; then
            echo "Branch name does not follow the required convention."
            exit 1
          fi
